version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo "Creating environment..."

  install:
    commands:
      - echo "Upgrade Pip and install packages"
      - pip install --upgrade pip
      - conda update conda
      - apt-get update && apt-get install -y build-essential
      - echo "channels:\n  - defaults\n\n  - conda-forge" > ~/.condarc
      - make setup
      - make install
      - mkdir -p ~/.aws/
      # Fake credentials needed by Moto for mocking Boto calls
      - echo "[default]\naws_access_key_id =  FakeKey\naws_secret_access_key = FakeKey\naws_session_token = FakeKey" > ~/.aws/credentials

  build:
    commands:
      - echo "Run lint and tests"
      - conda env list
      - export PATH=$PATH:/usr/local/envs/datadrivenproject/Scripts
      - make lint
      - PYTHONPATH=".";make test

  post_build:
    commands:
      - echo Build completed on `date`
